# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d44a2d00d29baa4b4421e2875a5d86e630d0240c32cc3b3df01dc1b62910e006581802b2a4b99c3188a131dfb8717e20ca80d6e0b97044ee31757e4d5164211

test:
  secret_key_base: 61db0eb684fd12e4c597ac0238f87991bc6de1612b78366b984e706ff101e1adbfc18f12dee75d84e5c4807ed38505d9e12a24d0e07790bf7d0c371eb2848c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
